# 엑셀파일 불러와서 csv 파일로 변환
* pandas, openpyxl 라이브러리 다운 필요
* to_csv(index=False)를 통해서 excel로 불러왔던 데이터프레임을 csv 파일로 변환

In [7]:
import pandas as pd

df = pd.read_excel("./202201_dropna.xlsx")

In [8]:
df.to_csv("./202201.csv", index=False, encoding="utf-8-sig")

In [9]:
df1 = pd.read_csv("./202201.csv", index_col=0, encoding="utf-8-sig")

In [1]:
# df1

## data_splitting.py 파일을 실행해서 데이터를 쪼갭니다.(해당 파일의 batch 라는 변수 값을 수정해서 몇 개씩 쪼갤지를 정합니다.)
* 예시 : batch =10000 이면, 10000개씩 쪼갠다는 의미/  총 60,000개의 데이터인 경우, batch=10000이면, 6개의 batch 가 생겨나는 거.
---

## address_api_V4.py 를 실행
### input을 입력해줘야 함.
1. 폴더명 (202201)
2. 세부 폴더명(202201 이라는 전체 데이터를 data_splitting.py로 쪼갠 이후에 생겨난 세부 데이터들의 폴더명을 입력)
**이 과정을 반복해서 전체 쪼개진 데이터에 대해서 주소 변환을 수행**
---

## 쪼개진 데이터를 merge
### 아래 코드 참조.

In [2]:
import pandas as pd

checking = pd.read_csv("./202201/2/2.csv", index_col=0)

In [4]:
checking["n_addr"]

연번
99646982    부산광역시 남구 수영로325번길 159-30
99646985     부산광역시 남구 황령대로319번가길 142
99646988           부산광역시 남구 장고개로 108
99646991        부산광역시 남구 전포대로20번길 15
99646994            부산광역시 남구 수영로 261
                      ...
99581402        부산광역시 수영구 감포로48번길 10
99428552         부산광역시 강서구 생곡산단1로 28
99406127     부산광역시 동래구 중앙대로1473번길 13
99327887           부산광역시 수영구 수영로 641
99256208         부산광역시 금정구 신천로 53-15
Name: n_addr, Length: 67, dtype: object

### 원본 데이터프레임과 주소변환이 완료된 데이터프레임을 concat 시켜서 변환된 데이터프레임이 비동기 처리로 인해서 인덱스의 순서가 뒤죽박죽이지는 않은지 확인해보기

In [11]:
import pandas as pd

df1 = pd.read_csv("./202201/1/1.csv")
df2 = pd.read_csv("./202201/1/final_address_1.csv")

In [1]:
# df1.head()

In [14]:
df_sim = pd.concat([df1.loc[:, "n_addr"], df2], axis=1)
df_sim

                       n_addr    시/도 시/군/구 읍/면/동
0        부산광역시 서구 대영로105번길 20  부산광역시    남구   대연동
1          부산광역시 서구 대영로 92-10  부산광역시  해운대구   반여동
2        부산광역시 서구 천마로186번길 25  부산광역시  부산진구   부전동
3       부산광역시 서구 충무대로177번길 13  부산광역시  부산진구   범천동
4            부산광역시 서구 충무대로 64  부산광역시   연제구   거제동
...                       ...    ...   ...   ...
4995        부산광역시 북구 금곡대로 166    NaN   NaN   NaN
4996       부산광역시 해운대구 달맞이길 30    NaN   NaN   NaN
4997       부산광역시 해운대구 달맞이길 23    NaN   NaN   NaN
4998  부산광역시 해운대구 송정중앙로15번길 41    NaN   NaN   NaN
4999       부산광역시 북구 화명신도시로 70    NaN   NaN   NaN

[5000 rows x 4 columns]

In [4]:
import pandas as pd

df = pd.read_csv('./202201.csv')
df

,연번,1.5 거주지 주소,1.7 구성원 시설명,1.8 감염취약시설 유형,1.9 등록장애인 여부,1.10 장애유형_지체,1.10 장애유형_정신 등,1.11 장애정도_중증,1.11 장애정도_경증,2.1 증상 유무,...,2.6 예방접종 4차 백신기타,2.6 예방접종 4차 접종일,2.6 예방접종 5차 백신종류,2.6 예방접종 5차 백신기타,2.6 예방접종 5차 접종일,2.7 과거 코로나 감염 여부,2.7 과거 코로나 감염 일자,3. 동거인 여부,3. 동거인 인원,n_addr
0,85642097,부산광역시 서구 대영로105번길 20 (동대신동2가) 101,NaN,NaN,아니요,No,No,No,No,없음,...,NaN,NaN,NaN,NaN,NaN,아니요,NaN,아니요,NaN,부산광역시 서구 대영로105번길 20
1,85640762,부산광역시 서구 대영로 92-10 (동대신동1가) .,NaN,NaN,아니요,No,No,No,No,있음,...,NaN,NaN,NaN,NaN,NaN,아니요,NaN,아니요,NaN,부산광역시 서구 대영로 92-10
2,85625612,부산광역시 서구 천마로186번길 25 (남부민동) .,NaN,NaN,아니요,No,No,No,No,없음,...,NaN,NaN,NaN,NaN,NaN,아니요,NaN,아니요,NaN,부산광역시 서구 천마로186번길 25
3,85623344,부산광역시 서구 충무대로177번길 13 (남부민동) 4층,NaN,NaN,아니요,No,No,No,No,없음,...,NaN,NaN,NaN,NaN,NaN,아니요,NaN,예,1.0,부산광역시 서구 충무대로177번길 13
4,85622684,"부산광역시 서구 충무대로 64 (암남동, 송도삼정비치) 정비치 906",NaN,NaN,아니요,No,No,No,No,없음,...,NaN,NaN,NaN,NaN,NaN,아니요,NaN,아니요,NaN,부산광역시 서구 충무대로 64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10062,99581402,"부산광역시 수영구 감포로48번길 10(민락동, 명신파크빌라) 301호",NaN,NaN,아니요,No,No,No,No,없음,...,NaN,NaN,NaN,NaN,NaN,아니요,NaN,예,3.0,부산광역시 수영구 감포로48번길 10
10063,99428552,부산광역시 강서구 생곡산단1로 28 (생곡동) 삼영엠티 기숙사,NaN,NaN,아니요,No,No,No,No,있음,...,NaN,NaN,NaN,NaN,NaN,아니요,NaN,아니요,NaN,부산광역시 강서구 생곡산단1로 28
10064,99406127,"부산광역시 동래구 중앙대로1473번길 13 (온천동, 벽산아스타) 101동 4902호",NaN,NaN,아니요,No,No,No,No,있음,...,NaN,NaN,NaN,NaN,NaN,예,2022년 04월,예,1.0,부산광역시 동래구 중앙대로1473번길 13
10065,99327887,"부산광역시 수영구 수영로 641(광안동, 힐탑더블시티) 101동 905호",NaN,NaN,아니요,No,No,No,No,없음,...,NaN,NaN,NaN,NaN,NaN,아니요,NaN,아니요,NaN,부산광역시 수영구 수영로 641
10066,99256208,부산광역시 금정구 신천로 53-15 (선동) 단독 주택,NaN,NaN,예,No,Yes,Yes,No,있음,...,NaN,NaN,NaN,NaN,NaN,예,2022년 10월,예,1.0,부산광역시 금정구 신천로 53-15

In [2]:
import pandas as pd

df1 = pd.read_csv('C:/Users/user/Desktop/address_test/202201/1/1.csv')
df2 = pd.read_csv('C:/Users/user/Desktop/address_test/202201/1/final_address_1.csv', index_col=0)

df3 = pd.concat([df1,df2], axis=1)
df3

,연번,1.5 거주지 주소,1.7 구성원 시설명,1.8 감염취약시설 유형,1.9 등록장애인 여부,1.10 장애유형_지체,1.10 장애유형_정신 등,1.11 장애정도_중증,1.11 장애정도_경증,2.1 증상 유무,...,2.6 예방접종 5차 백신기타,2.6 예방접종 5차 접종일,2.7 과거 코로나 감염 여부,2.7 과거 코로나 감염 일자,3. 동거인 여부,3. 동거인 인원,n_addr,시/도,시/군/구,읍/면/동
0,85642097,부산광역시 서구 대영로105번길 20 (동대신동2가) 101,NaN,NaN,아니요,No,No,No,No,없음,...,NaN,NaN,아니요,NaN,아니요,NaN,부산광역시 서구 대영로105번길 20,부산광역시,서구,동대신동2가
1,85640762,부산광역시 서구 대영로 92-10 (동대신동1가) .,NaN,NaN,아니요,No,No,No,No,있음,...,NaN,NaN,아니요,NaN,아니요,NaN,부산광역시 서구 대영로 92-10,부산광역시,서구,동대신동1가
2,85625612,부산광역시 서구 천마로186번길 25 (남부민동) .,NaN,NaN,아니요,No,No,No,No,없음,...,NaN,NaN,아니요,NaN,아니요,NaN,부산광역시 서구 천마로186번길 25,부산광역시,서구,남부민동
3,85623344,부산광역시 서구 충무대로177번길 13 (남부민동) 4층,NaN,NaN,아니요,No,No,No,No,없음,...,NaN,NaN,아니요,NaN,예,1.0,부산광역시 서구 충무대로177번길 13,부산광역시,서구,남부민동
4,85622684,"부산광역시 서구 충무대로 64 (암남동, 송도삼정비치) 정비치 906",NaN,NaN,아니요,No,No,No,No,없음,...,NaN,NaN,아니요,NaN,아니요,NaN,부산광역시 서구 충무대로 64,부산광역시,서구,암남동
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10062,99581402,"부산광역시 수영구 감포로48번길 10(민락동, 명신파크빌라) 301호",NaN,NaN,아니요,No,No,No,No,없음,...,NaN,NaN,아니요,NaN,예,3.0,부산광역시 수영구 감포로48번길 10,부산광역시,수영구,민락동
10063,99428552,부산광역시 강서구 생곡산단1로 28 (생곡동) 삼영엠티 기숙사,NaN,NaN,아니요,No,No,No,No,있음,...,NaN,NaN,아니요,NaN,아니요,NaN,부산광역시 강서구 생곡산단1로 28,부산광역시,강서구,생곡동
10064,99406127,"부산광역시 동래구 중앙대로1473번길 13 (온천동, 벽산아스타) 101동 4902호",NaN,NaN,아니요,No,No,No,No,있음,...,NaN,NaN,예,2022년 04월,예,1.0,부산광역시 동래구 중앙대로1473번길 13,부산광역시,동래구,온천동
10065,99327887,"부산광역시 수영구 수영로 641(광안동, 힐탑더블시티) 101동 905호",NaN,NaN,아니요,No,No,No,No,없음,...,NaN,NaN,아니요,NaN,아니요,NaN,부산광역시 수영구 수영로 641,부산광역시,수영구,광안동
10066,99256208,부산광역시 금정구 신천로 53-15 (선동) 단독 주택,NaN,NaN,예,No,Yes,Yes,No,있음,...,NaN,NaN,예,2022년 10월,예,1.0,부산광역시 금정구 신천로 53-15,부산광역시,금정구,선동

In [4]:
df3.to_excel('./202201_final.xlsx')