# 엑셀파일 불러와서 csv 파일로 변환
* pandas, openpyxl 라이브러리 다운 필요
* to_csv(index=False)를 통해서 excel로 불러왔던 데이터프레임을 csv 파일로 변환

In [1]:
import pandas as pd

df = pd.read_excel("./202202_dropna.xlsx")

In [2]:
df.to_csv("./202202.csv", index=False, encoding="utf-8-sig")

In [4]:
df1 = pd.read_csv("./202202.csv", index_col=0, encoding="utf-8-sig", low_memory=False)

In [6]:
df1.head()

,1.5 거주지 주소,1.7 구성원 시설명,1.8 감염취약시설 유형,1.9 등록장애인 여부,1.10 장애유형_지체,1.10 장애유형_정신 등,1.11 장애정도_중증,1.11 장애정도_경증,2.1 증상 유무,2.2 증상발생일,...,2.6 예방접종 4차 백신기타,2.6 예방접종 4차 접종일,2.6 예방접종 5차 백신종류,2.6 예방접종 5차 백신기타,2.6 예방접종 5차 접종일,2.7 과거 코로나 감염 여부,2.7 과거 코로나 감염 일자,3. 동거인 여부,3. 동거인 인원,n_addr
연번,,,,,,,,,,,,,,,,,,,,,
100045691,부산광역시 중구 보수대로142번길 7(보수동1가) 302호,NaN,NaN,아니요,No,No,No,No,있음,2023-02-03,...,NaN,NaN,NaN,NaN,NaN,아니요,NaN,예,1,부산광역시 중구 보수대로142번길 7
100045637,부산광역시 북구 금곡대로123번길 30-20(덕천동) 덕천동,NaN,NaN,아니요,No,No,No,No,있음,2023-02-03,...,NaN,NaN,NaN,NaN,NaN,아니요,NaN,예,2,부산광역시 북구 금곡대로123번길 30-20
100045097,"부산광역시 북구 백양대로1016번길 10 (구포동, 삼정그린코아) 106-2004",NaN,NaN,아니요,No,No,No,No,있음,2023-02-02,...,NaN,NaN,NaN,NaN,NaN,아니요,NaN,예,1,부산광역시 북구 백양대로1016번길 10
100045091,부산광역시 서구 암남공원로 522 (암남동) 송도요양병원,송도요양병원,요양병원,아니요,No,No,No,No,있음,2023-02-04,...,NaN,2022-05-06,NaN,NaN,NaN,아니요,NaN,아니요,NaN,부산광역시 서구 암남공원로 522
100044959,부산광역시 강서구 명지국제5로 29 (명지동 명지국제신도시호반베르디움1차) 106-...,NaN,NaN,아니요,No,No,No,No,있음,2023-02-03,...,NaN,NaN,NaN,NaN,NaN,아니요,NaN,예,3,부산광역시 강서구 명지국제5로 29

---

### 원본 데이터프레임과 주소변환이 완료된 데이터프레임을 concat 시켜서 변환된 데이터프레임의 인덱스가 비동기 처리로 인해서 섞여있는 건 아닌지 확인해보기

In [11]:
import pandas as pd

df1 = pd.read_csv("./202201/1/1.csv")
df2 = pd.read_csv("./202201/1/final_address_1.csv")

In [14]:
df_sim = pd.concat([df1.loc[:, "n_addr"], df2], axis=1)
df_sim

                       n_addr    시/도 시/군/구 읍/면/동
0        부산광역시 서구 대영로105번길 20  부산광역시    남구   대연동
1          부산광역시 서구 대영로 92-10  부산광역시  해운대구   반여동
2        부산광역시 서구 천마로186번길 25  부산광역시  부산진구   부전동
3       부산광역시 서구 충무대로177번길 13  부산광역시  부산진구   범천동
4            부산광역시 서구 충무대로 64  부산광역시   연제구   거제동
...                       ...    ...   ...   ...
4995        부산광역시 북구 금곡대로 166    NaN   NaN   NaN
4996       부산광역시 해운대구 달맞이길 30    NaN   NaN   NaN
4997       부산광역시 해운대구 달맞이길 23    NaN   NaN   NaN
4998  부산광역시 해운대구 송정중앙로15번길 41    NaN   NaN   NaN
4999       부산광역시 북구 화명신도시로 70    NaN   NaN   NaN

[5000 rows x 4 columns]

---

## 변환 후 merge
### 202202/2/1.csv
###

In [17]:
import pandas as pd
import os

file_list = os.listdir('./202202/')
print(file_list)

for i in range(1, len(file_list)+1):
    b_path = os.path.join(file_list, i)
    name = f'{i}.csv'
    name_a = f'final_address_{i}.csv'
    main_name = os.path.join(b_path, name)
    after_name = os.path.join(b_path, name_a)
    df1 = pd.read_csv(main_name)
    df2 = pd.read_csv(after_name, index_col=0)
    df3 = pd.concat([df1, df2], axis=1)
    df3.to_csv(os.path.join(b_path, f'{i}_merged.csv'))

['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '2', '3', '4', '5', '6', '7', '8', '9']
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18

In [4]:
df3.to_excel('./202201_final.xlsx')

## 엑셀 파일 불러와서 csv 파일로 변환

In [2]:
import pandas as pd
df = pd.read_excel('./202202_dropna.xlsx')
df

,연번,1.5 거주지 주소,1.7 구성원 시설명,1.8 감염취약시설 유형,1.9 등록장애인 여부,1.10 장애유형_지체,1.10 장애유형_정신 등,1.11 장애정도_중증,1.11 장애정도_경증,2.1 증상 유무,...,2.6 예방접종 4차 백신기타,2.6 예방접종 4차 접종일,2.6 예방접종 5차 백신종류,2.6 예방접종 5차 백신기타,2.6 예방접종 5차 접종일,2.7 과거 코로나 감염 여부,2.7 과거 코로나 감염 일자,3. 동거인 여부,3. 동거인 인원,n_addr
0,100045691,부산광역시 중구 보수대로142번길 7(보수동1가) 302호,NaN,NaN,아니요,No,No,No,No,있음,...,NaN,NaN,NaN,NaN,NaN,아니요,NaN,예,1,부산광역시 중구 보수대로142번길 7
1,100045637,부산광역시 북구 금곡대로123번길 30-20(덕천동) 덕천동,NaN,NaN,아니요,No,No,No,No,있음,...,NaN,NaN,NaN,NaN,NaN,아니요,NaN,예,2,부산광역시 북구 금곡대로123번길 30-20
2,100045097,"부산광역시 북구 백양대로1016번길 10 (구포동, 삼정그린코아) 106-2004",NaN,NaN,아니요,No,No,No,No,있음,...,NaN,NaN,NaN,NaN,NaN,아니요,NaN,예,1,부산광역시 북구 백양대로1016번길 10
3,100045091,부산광역시 서구 암남공원로 522 (암남동) 송도요양병원,송도요양병원,요양병원,아니요,No,No,No,No,있음,...,NaN,2022-05-06,NaN,NaN,NaN,아니요,NaN,아니요,NaN,부산광역시 서구 암남공원로 522
4,100044959,부산광역시 강서구 명지국제5로 29 (명지동 명지국제신도시호반베르디움1차) 106-...,NaN,NaN,아니요,No,No,No,No,있음,...,NaN,NaN,NaN,NaN,NaN,아니요,NaN,예,3,부산광역시 강서구 명지국제5로 29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171805,8489024,"부산광역시 수영구 민락수변로7번길 60(민락동, e편한세상 광안비치) 102동 1902호",NaN,NaN,아니요,No,No,No,No,있음,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,예,3,부산광역시 수영구 민락수변로7번길 60
171806,8307317,"부산광역시 수영구 광안로 20(광안동, 부산 광안동 쌍용 예가 디 오션) 103동 ...",NaN,NaN,아니요,No,No,No,No,있음,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,예,2,부산광역시 수영구 광안로 20
171807,7989605,"부산광역시 부산진구 전포대로171번길 12(전포동, 서면세종그랑시아) A동2004호",NaN,NaN,아니요,No,No,No,No,있음,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,예,2,부산광역시 부산진구 전포대로171번길 12
171808,7966016,부산광역시 부산진구 동성로112번나길 5(전포동) 부산진구 동성로 112번나길5 천지탕,NaN,NaN,아니요,No,No,No,No,없음,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,아니요,NaN,부산광역시 부산진구 동성로112번나길 5
171809,6314018,부산광역시 남구 용호로177번길 10(용호동) 2층,NaN,NaN,아니요,No,No,No,No,있음,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,예,1,부산광역시 남구 용호로177번길 10

In [8]:
df.to_csv('./202202.csv', index=False, encoding = 'utf-8-sig')
df2 = pd.read_csv('./202202.csv', index_col=0, encoding ='utf-8-sig', low_memory=False)

In [18]:
df2

NameError: name 'df2' is not defined